/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jvm_lab_NativeDemo */

#ifndef _Included_com_example_jvm_lab_NativeDemo
#define _Included_com_example_jvm_lab_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jvm_lab_NativeDemo
 * Method:    encryptData
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jvm_lab_NativeDemo_encryptData
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
