/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jvm_lab_DateTimeUtils */

#ifndef _Included_com_example_jvm_lab_DateTimeUtils
#define _Included_com_example_jvm_lab_DateTimeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jvm_lab_DateTimeUtils
 * Method:    getSystemTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jvm_lab_DateTimeUtils_getSystemTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
